### ISSUE TITLE
ISE when trying to edit compute profile

### ISSUE THREAD

**Issue by adamruzicka** [stejskalleos/foreman_google#45]
```
2022-06-24T15:43:00 [I|app|29540fab] Completed 500 Internal Server Error in 989ms (ActiveRecord: 9.7ms | Allocations: 113938)
 29540fab | 
 29540fab | 
2022-06-24T15:43:00 [F|app|29540fab]   
 29540fab | ActionView::Template::Error (undefined method `size_gb' for #<Google::Cloud::Compute::V1::AttachedDisk:0x00000000117beec0>):
 29540fab |     1: <%= text_f f, :size_gb, :class => "col-md-2", :label => _("Size (GB)"), :label_size => "col-md-2", :onchange => 'tfm.computeResource.capacityEdit(this)' %>
 29540fab |   
 29540fab | app/helpers/form_helper.rb:6:in `block in text_f'
 29540fab | app/helpers/form_helper.rb:384:in `block (3 levels) in field'
 29540fab | app/helpers/form_helper.rb:380:in `block (2 levels) in field'
 29540fab | app/helpers/form_helper.rb:378:in `block in field'
 29540fab | app/helpers/form_helper.rb:377:in `field'
 29540fab | app/helpers/form_helper.rb:3:in `text_f'
 29540fab | app/views/compute_resources_vms/form/gce/_volume.html.erb:1
 29540fab | app/helpers/layout_helper.rb:221:in `block (2 levels) in new_child_fields_template'
 29540fab | app/helpers/layout_helper.rb:220:in `block in new_child_fields_template'
 29540fab | app/helpers/layout_helper.rb:219:in `new_child_fields_template'
 29540fab | app/views/compute_resources_vms/form/_volumes.html.erb:6
 29540fab | app/views/compute_resources_vms/form/_volumes.html.erb:3
 29540fab | app/views/compute_attributes/_compute_form.html.erb:9
 29540fab | app/views/compute_attributes/_form.html.erb:8
 29540fab | app/views/compute_attributes/_form.html.erb:7
 29540fab | app/helpers/form_helper.rb:287:in `form_for'
 29540fab | app/views/compute_attributes/_form.html.erb:1
 29540fab | app/views/compute_attributes/new.html.erb:23
```

**Comment by stejskalleos** [comment]
Fixed
